export const SEED_RESPONSES = [
  // Inglés (en)
  { reading: 'It is certain.', category: 'positive', locale: 'en' },
  { reading: 'It is decidedly so.', category: 'positive', locale: 'en' },
  { reading: 'Without a doubt.', category: 'positive', locale: 'en' },
  { reading: 'Yes, definitely.', category: 'positive', locale: 'en' },
  { reading: 'You may rely on it.', category: 'positive', locale: 'en' },
  { reading: 'As I see it, yes.', category: 'positive', locale: 'en' },
  { reading: 'Most likely.', category: 'positive', locale: 'en' },
  { reading: 'Outlook good.', category: 'positive', locale: 'en' },
  { reading: 'Yes.', category: 'positive', locale: 'en' },
  { reading: 'Signs point to yes.', category: 'positive', locale: 'en' },
  { reading: 'Reply hazy, try again.', category: 'neutral', locale: 'en' },
  { reading: 'Ask again later.', category: 'neutral', locale: 'en' },
  { reading: 'Better not tell you now.', category: 'neutral', locale: 'en' },
  { reading: 'Cannot predict now.', category: 'neutral', locale: 'en' },
  { reading: 'Concentrate and ask again.', category: 'neutral', locale: 'en' },
  { reading: 'Don\'t count on it.', category: 'negative', locale: 'en' },
  { reading: 'My reply is no.', category: 'negative', locale: 'en' },
  { reading: 'My sources say no.', category: 'negative', locale: 'en' },
  { reading: 'Outlook not so good.', category: 'negative', locale: 'en' },
  { reading: 'Very doubtful.', category: 'negative', locale: 'en' },

  // Español (es)
  { reading: 'Es cierto.', category: 'positive', locale: 'es' },
  { reading: 'Decididamente sí.', category: 'positive', locale: 'es' },
  { reading: 'Sin lugar a dudas.', category: 'positive', locale: 'es' },
  { reading: 'Sí, definitivamente.', category: 'positive', locale: 'es' },
  { reading: 'Puedes contar con ello.', category: 'positive', locale: 'es' },
  { reading: 'Como yo lo veo, sí.', category: 'positive', locale: 'es' },
  { reading: 'Muy probable.', category: 'positive', locale: 'es' },
  { reading: 'Las perspectivas son buenas.', category: 'positive', locale: 'es' },
  { reading: 'Sí.', category: 'positive', locale: 'es' },
  { reading: 'Las señales apuntan a que sí.', category: 'positive', locale: 'es' },
  { reading: 'Respuesta confusa, intenta de nuevo.', category: 'neutral', locale: 'es' },
  { reading: 'Pregunta de nuevo más tarde.', category: 'neutral', locale: 'es' },
  { reading: 'Mejor no decírtelo ahora.', category: 'neutral', locale: 'es' },
  { reading: 'No puedo predecirlo ahora.', category: 'neutral', locale: 'es' },
  { reading: 'Concéntrate y pregunta de nuevo.', category: 'neutral', locale: 'es' },
  { reading: 'No cuentes con ello.', category: 'negative', locale: 'es' },
  { reading: 'Mi respuesta es no.', category: 'negative', locale: 'es' },
  { reading: 'Mis fuentes dicen que no.', category: 'negative', locale: 'es' },
  { reading: 'Las perspectivas no son buenas.', category: 'negative', locale: 'es' },
  { reading: 'Muy dudoso.', category: 'negative', locale: 'es' },


];